import {
  HOST,
  PORT,
  APIKEYFIREBASE,
  AUTHDOMAINFIREBASE,
  PROJECTIDFIREBASE,
  STORAGEBUCKETFIREBASE,
  MESSAGINGSENDERFIREBASE,
  APPIDFIREBASE,
  MEASUREMENTIDFIREBASE,
  DATABASEURLFIREBASE,
} from 'react-native-dotenv';

export default {
  PORT,
  HOST,
  APIKEYFIREBASE,
  AUTHDOMAINFIREBASE,
  PROJECTIDFIREBASE,
  STORAGEBUCKETFIREBASE,
  MESSAGINGSENDERFIREBASE,
  APPIDFIREBASE,
  MEASUREMENTIDFIREBASE,
  DATABASEURLFIREBASE,
};
