import env from '../env';

const {
  APIKEYFIREBASE,
  APPIDFIREBASE,
  AUTHDOMAINFIREBASE,
  DATABASEURLFIREBASE,
  MEASUREMENTIDFIREBASE,
  MESSAGINGSENDERFIREBASE,
  PROJECTIDFIREBASE,
  STORAGEBUCKETFIREBASE,
} = env;

const firebaseConfig = {
  apiKey: APIKEYFIREBASE,
  authDomain: AUTHDOMAINFIREBASE,
  projectId: PROJECTIDFIREBASE,
  storageBucket: STORAGEBUCKETFIREBASE,
  messagingSenderId: MESSAGINGSENDERFIREBASE,
  appId: APPIDFIREBASE,
  measurementId: MEASUREMENTIDFIREBASE,
  databaseURL: DATABASEURLFIREBASE,
};

export default firebaseConfig;
